Repository SOPT-all/35-COLLABORATION-ANDROID-KAKAOWEBTOON, pull requests merged in 2024-11, with the labels that each got.

#4 [init] 아이콘 초기세팅
  app/src/main/res/drawable/ic_bottom_nav_gift_activate.xml
  app/src/main/res/drawable/ic_bottom_nav_gift_disabled.xml
  app/src/main/res/drawable/ic_bottom_nav_rank_activate.xml
  app/src/main/res/drawable/ic_bottom_nav_rank_disabled.xml
  app/src/main/res/drawable/ic_bottom_nav_storage_activate.xml
  app/src/main/res/drawable/ic_bottom_nav_storage_disabled.xml
  app/src/main/res/drawable/ic_bottom_nav_timetable_activate.xml
  app/src/main/res/drawable/ic_bottom_nav_timetable_disabled.xml
  app/src/main/res/drawable/ic_chip_clock.xml
  app/src/main/res/drawable/ic_episode_arrow_left.xml
  app/src/main/res/drawable/ic_episode_arrow_updown.xml
  app/src/main/res/drawable/ic_episode_genre.xml
  app/src/main/res/drawable/ic_episode_good.xml
  app/src/main/res/drawable/ic_episode_heart.xml
  app/src/main/res/drawable/ic_episode_list.xml
  app/src/main/res/drawable/ic_episode_see_more.xml
  app/src/main/res/drawable/ic_episode_view.xml
  app/src/main/res/drawable/ic_home_arrow_bottom_white_12.xml
  app/src/main/res/drawable/ic_home_arrow_right.xml
  app/src/main/res/drawable/ic_home_card_logo.xml
  app/src/main/res/drawable/ic_home_vertical_line.xml
  app/src/main/res/drawable/ic_search_arrow_under_white_18.xml
  app/src/main/res/drawable/ic_search_close.xml
  app/src/main/res/drawable/ic_search_subtraction.xml
  app/src/main/res/drawable/ic_storage_expandarrow.png
  app/src/main/res/drawable/ic_storage_trash.png
  app/src/main/res/drawable/ic_topbar_coin.xml
  app/src/main/res/drawable/ic_topbar_logo.xml
  app/src/main/res/drawable/ic_topbar_menu.xml
  app/src/main/res/drawable/ic_topbar_search.xml
Labels: init

#10 [init] 프로젝트 구조 초기세팅
  .github/workflows/android_ci.yml
  README.md
  app/build.gradle.kts
  app/src/androidTest/java/com/example/kakaowebtoon/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kakaowebtoon/KakaoWebtoonApp.kt
  app/src/main/java/com/example/kakaowebtoon/data/datalocal/datasource/DummyLocalDataSource.kt
  app/src/main/java/com/example/kakaowebtoon/data/datalocal/datasourceimpl/DummyLocalDataSourceImpl.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/datasource/DummyRemoteDataSource.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/datasourceimpl/DummyRemoteDataSourceImpl.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/model/response/DummyResponseDto.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/service/DummyService.kt
  app/src/main/java/com/example/kakaowebtoon/data/mapper/DataMapper.kt
  app/src/main/java/com/example/kakaowebtoon/data/repositoryimpl/DummyRepositoryImpl.kt
  app/src/main/java/com/example/kakaowebtoon/di/DataSourceModule.kt
  app/src/main/java/com/example/kakaowebtoon/di/NetworkModule.kt
  app/src/main/java/com/example/kakaowebtoon/di/RepositoryModule.kt
  app/src/main/java/com/example/kakaowebtoon/di/ServiceModule.kt
  app/src/main/java/com/example/kakaowebtoon/domain/model/DummyData.kt
  app/src/main/java/com/example/kakaowebtoon/domain/repository/DummyRepository.kt
  app/src/main/java/com/example/kakaowebtoon/domain/usecase/DummyUseCase.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/episode/EpisodeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/episode/EpisodeViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/home/HomeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/main/MainActivity.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/main/MainScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/main/MainViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/search/SearchScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/search/SearchViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/storage/StorageScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/storage/StorageViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/util/ModifierExt.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Color.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Theme.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Type.kt
  app/src/test/java/com/example/kakaowebtoon/ExampleUnitTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: init

#6 [init] Color scheme 초기세팅
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Color.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Theme.kt
Labels: init

#8 [init] Font 초기세팅
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Theme.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Type.kt
  app/src/main/res/font/roboto_bold.ttf
  app/src/main/res/font/roboto_light.ttf
  app/src/main/res/font/roboto_medium.ttf
  app/src/main/res/font/roboto_regular.ttf
Labels: init

#13 [feat] 공통 Indicator 컴포넌트 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kakaowebtoon/domain/model/IndicatorContents.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/type/IndicatorType.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/KakaoWebtoonIndicator.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/EpisodeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/EpisodeViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/MainViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/SearchScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/SearchViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/storage/StorageScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/storage/StorageViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Color.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Theme.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Type.kt
  gradle/libs.versions.toml
Labels: feat

#17 [feat] 공통 TopBar 컴포넌트 구현
  app/src/main/java/com/example/kakaowebtoon/presentation/type/TopBarType.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/KakaoWebtoonTopBar.kt
  app/src/main/res/drawable/ic_episode_heart.xml
  app/src/main/res/drawable/ic_topbar_heart.xml
  app/src/main/res/values/strings.xml
Labels: feat

#16 [feat] Bottom Navigation Bar 및 Main Navigator 구현
  app/build.gradle.kts
  app/src/main/java/com/example/kakaowebtoon/presentation/model/Route.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/type/MainBottomNavType.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/navigation/EpisodeNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/gift/GiftScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/gift/navigation/GiftNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/component/MainBottomNavBar.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/component/MainNavHost.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/rank/RankScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/rank/navigation/RankNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/navigation/SearchNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/storage/navigation/StorageNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Theme.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Type.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: feat

#21 [feat] Storage View 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kakaowebtoon/domain/model/IndicatorContents.kt
  app/src/main/java/com/example/kakaowebtoon/domain/model/WebtoonCard.kt
  app/src/main/java/com/example/kakaowebtoon/domain/util/Constraints.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/type/IndicatorType.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/type/StorageButtonType.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/type/TopBarType.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/KakaoWebtoonIndicator.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/KakaoWebtoonTopBar.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/card/KakaoWebtoonCard.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/indicator/KakaoWebtoonIndicator.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/tags/KakaoWebtoonClockTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/tags/KakaoWebtoonFreeLaterTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/tags/KakaoWebtoonFreeTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/tags/KakaoWebtoonGenreTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/tags/KakaoWebtoonUpTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/component/MainNavHost.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/SearchScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/SearchViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/component/SearchViewIndicator.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/component/SerachTextField.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/navigation/SearchNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/storage/StorageScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/storage/StorageViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/storage/component/StorageButton.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/storage/navigation/StorageNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/util/ModifierExt.kt
  app/src/main/java/com/example/kakaowebtoon/ui/theme/Type.kt
  app/src/main/res/drawable/img_dummy_webtoon_card.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feat

#25 [chore] Search View 리뷰 적용
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/KakaoWebtoonTopBar.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/tags/KakaoWebtoonClockTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/tags/KakaoWebtoonFreeLaterTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/tags/KakaoWebtoonFreeTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/tags/KakaoWebtoonGenreTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/tags/KakaoWebtoonUpTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/SearchScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/SearchViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/component/SearchViewIndicator.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/component/SerachTextField.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/util/ModifierExt.kt
Labels: feat

#24 [feat] Home View 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kakaowebtoon/domain/util/Constraints.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/type/HomeDayType.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/type/HomeGenreType.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/indicator/KakaoWebtoonIndicator.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeBanner.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeCardEmptyView.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeCardView.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeFilterTextButton.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeFooter.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeGenreTabRow.kt
  app/src/main/res/drawable/img_home_ad.png
  app/src/main/res/drawable/img_home_banner_background.png
  app/src/main/res/drawable/img_home_banner_character.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feat

#23 [feat] Episode View 구현
  app/src/main/java/com/example/kakaowebtoon/domain/model/EpisodeCard.kt
  app/src/main/java/com/example/kakaowebtoon/domain/model/WebtoonDetail.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/EpisodeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/EpisodeViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/component/EpisodeDetail.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/component/EpisodeDetailCard.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/component/EpisodeFreeTag.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/component/EpisodeRow.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/navigation/EpisodeNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/gift/GiftScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/gift/navigation/GiftNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/component/MainNavHost.kt
  app/src/main/res/values/strings.xml
Labels: feat

#35 [feat] 웹툰 세부 디테일 조회 API 연동
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/datasource/EpisodeRemoteDataSource.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/datasourceimpl/EpisodeRemoteDataSourceImpl.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/model/response/EpisodeDetailResponseDto.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/service/EpisodeService.kt
  app/src/main/java/com/example/kakaowebtoon/data/repositoryimpl/EpisodeRepositoryImpl.kt
  app/src/main/java/com/example/kakaowebtoon/di/DataSourceModule.kt
  app/src/main/java/com/example/kakaowebtoon/di/RepositoryModule.kt
  app/src/main/java/com/example/kakaowebtoon/di/ServiceModule.kt
  app/src/main/java/com/example/kakaowebtoon/domain/repository/EpisodeRepository.kt
  app/src/main/java/com/example/kakaowebtoon/domain/usecase/EpisodeDetailUseCase.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/EpisodeViewModel.kt
Labels: feat

#31 [refactor] SearchTextField 터치 영역 수정
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/component/SerachTextField.kt
Labels: refactor

#36 [chore] Episode View 수정
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/EpisodeScreen.kt
Labels: chore

#38 [feat] 웹툰 회차 조회 API 연동
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/datasource/EpisodeRemoteDataSource.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/datasourceimpl/EpisodeRemoteDataSourceImpl.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/model/response/EpisodesResponseDto.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/service/EpisodeService.kt
  app/src/main/java/com/example/kakaowebtoon/data/repositoryimpl/EpisodeRepositoryImpl.kt
  app/src/main/java/com/example/kakaowebtoon/domain/repository/EpisodeRepository.kt
  app/src/main/java/com/example/kakaowebtoon/domain/usecase/EpisodesUseCase.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/EpisodeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/EpisodeViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/episode/component/EpisodeDetailCard.kt
Labels: feat

#40 [feat] 검색 뷰와 에피소드 뷰 연결 feat
  app/src/main/java/com/example/kakaowebtoon/domain/util/Constraints.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/home/component/HomeCardView.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/component/MainNavHost.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/SearchScreen.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/navigation/SearchNavigation.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/util/Constraints.kt
  app/src/main/res/values/strings.xml
Labels: feat

#42 [feat] 더미 파일 삭제
  app/src/main/java/com/example/kakaowebtoon/data/datalocal/datasource/DummyLocalDataSource.kt
  app/src/main/java/com/example/kakaowebtoon/data/datalocal/datasourceimpl/DummyLocalDataSourceImpl.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/datasource/DummyRemoteDataSource.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/datasourceimpl/DummyRemoteDataSourceImpl.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/model/response/DummyResponseDto.kt
  app/src/main/java/com/example/kakaowebtoon/data/dataremote/service/DummyService.kt
  app/src/main/java/com/example/kakaowebtoon/data/mapper/DataMapper.kt
  app/src/main/java/com/example/kakaowebtoon/data/repositoryimpl/DummyRepositoryImpl.kt
  app/src/main/java/com/example/kakaowebtoon/di/DataSourceModule.kt
  app/src/main/java/com/example/kakaowebtoon/di/RepositoryModule.kt
  app/src/main/java/com/example/kakaowebtoon/di/ServiceModule.kt
  app/src/main/java/com/example/kakaowebtoon/domain/model/DummyData.kt
  app/src/main/java/com/example/kakaowebtoon/domain/repository/DummyRepository.kt
  app/src/main/java/com/example/kakaowebtoon/domain/usecase/DummyUseCase.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/component/card/KakaoWebtoonCard.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/main/MainViewModel.kt
  app/src/main/java/com/example/kakaowebtoon/presentation/ui/search/SearchViewModel.kt
  app/src/main/res/drawable/img_dummy_card1.png
  app/src/main/res/drawable/img_dummy_card2.png
Labels: feat

#43 Update README.md
  README.md
Labels: documentation
